version: "3"

services:
  gpt-engineer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    stdin_open: true
    tty: true
    # Set the API key from the .env file
    env_file:
      - .env
    ##  OR set the API key directly
    # environment:
      # - OPENAI_API_KEY=YOUR_API_KEY
    image: ghcr.io/jinyoung/gpt-engineer:v5
    command: ["-c"]
    volumes:
      - ./projects/example:/project
